CC3XX: Fix build error for dpa_hardened_word_copy
Fix the following [-Wimplicit-function-declaration] error:
cc3xx/common/cc3xx_stdlib.c:61:5:
   error: implicit declaration of function 'dpa_hardened_word_copy'
   61 |     dpa_hardened_word_copy(dst, src, word_count);

by adding the missing header file.

Signed-off-by: Nicola Mazzucato <nicola.mazzucato@arm.com>
Change-Id: I229349110b186bf684375d8674e593e449fd8682