RSE: supply rdv3 with missing #include directive
Commit 983b0faa8c7a ("RSE: Integrate ATU driver changes", 2025-09-21)
introduced two atu_rse_map_addr_to_log_addr() calls to
"platform/ext/target/arm/rse/neoverse_rd/rdv3/host_system.c". Those break
the build for me -- using gcc (Ubuntu 13.3.0-6ubuntu2~24.04) 13.3.0 --,
because "-Wall" implies "-Wimplicit" implies
"Wimplicit-function-declaration":

> platform/ext/target/arm/rse/neoverse_rd/rdv3/host_system.c: In function 'noc_s3_pre_init':
> platform/ext/target/arm/rse/neoverse_rd/rdv3/host_system.c:38:15: error: implicit declaration of function 'atu_rse_map_addr_to_log_addr' [-Wimplicit-function-declaration]
>    38 |     atu_err = atu_rse_map_addr_to_log_addr(&ATU_DEV_S, noc_s3_phys_address, HOST_NOC_S3_BASE,
>       |               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
> platform/ext/target/arm/rse/neoverse_rd/rdv3/host_system.c: In function 'noc_s3_post_init':
> platform/ext/target/arm/rse/neoverse_rd/rdv3/host_system.c:55:15: error: implicit declaration of function 'atu_rse_free_addr' [-Wimplicit-function-declaration]
>    55 |     atu_err = atu_rse_free_addr(&ATU_DEV_S, HOST_NOC_S3_BASE);
>       |               ^~~~~~~~~~~~~~~~~

Include "atu_rse_lib.h" for the function declaration.

At the same time, keep the private header #include directives sorted.

Change-Id: Ica22c5c3b0a2302de27527960b8d52a491f06c76
Signed-off-by: Laszlo Ersek <laszlo.ersek@arm.com>