PSE84: Add missing include
GET_CURRENT_COMPONENT is #defined in current.h. Without this include,
warnings may be generated:
.../platform/ext/target/infineon/common/spe/svc/platform_svc_handler.c:26:42: error: implicit declaration of function 'GET_CURRENT_COMPONENT' [-Wimplicit-function-declaration]
   26 |     struct partition_t *curr_partition = GET_CURRENT_COMPONENT();
      |                                          ^~~~~~~~~~~~~~~~~~~~~

Change-Id: I87eaa727b9f759b3d33562817eb0575e183bc914
Signed-off-by: Chris Brand <chris.brand@cypress.com>