Crypto: Link TF-PSA-Crypto with TF-M runtime
Make tfm_sprt a link-only dependency of crypto_service_tfpsacrypto
so that the TF-M crt_exit.c implementation satisfies mbedtls_exit()
calls from the buffer allocator.

Otherwise, there are multiple possible archive orderings that could be
chosen. If libtfm_sprt.a is not linked after the TF-PSA-Crypto archive
then the link will fail with the following error:
.../arm-none-eabi/bin/ld: partitions/crypto/tfpsacrypto/core/libtfpsacrypto.a(memory_buffer_alloc.o): in function `buffer_alloc_calloc':
.../lib/ext/tf-psa-crypto-src/platform/memory_buffer_alloc.c:246:(.text.buffer_alloc_calloc+0x56): undefined reference to `exit'
.../arm-none-eabi/bin/ld: partitions/crypto/tfpsacrypto/core/libtfpsacrypto.a(memory_buffer_alloc.o): in function `buffer_alloc_free':
.../lib/ext/tf-psa-crypto-src/platform/memory_buffer_alloc.c:376:(.text.buffer_alloc_free+0x24): undefined reference to `exit'

Change-Id: I7a5774b07ad06d3801eb4327c3bf5b51ef12fe7d
Signed-off-by: Chris Brand <chris.brand@cypress.com>