Exception: Platform-specific exception info store/dump HAL API
This patch introduces a platform specific exception info store/dump
HAL API.
Set PLATFORM_EXCEPTION_INFO to 1 and provide an implementation of
tfm_hal_platform_exception_info().
tfm_hal_platform_exception_info() is called by EXCEPTION_INFO.

Change-Id: Ibc96f6ec8918008a26613a59498ec051343066c8
Co-authored-by: Roman Mazurak <roman.mazurak@infineon.com>
Signed-off-by: Chris Brand <chris.brand@cypress.com>