Platform: nxp/frdmmcxn947: add missing utilities header
Add missing header for tfm_core_panic() prototype. A build error
occurred when e5d803c revealed the absence of utilities.h:

platform/ext/target/nxp/common/tfm_hal_isolation.c:716:5: error:
implicit declaration of function 'tfm_core_panic'
[-Wimplicit-function-declaration]
    716 |     tfm_core_panic();
        |     ^~~~~~~~~~~~~~

Change-Id: I211071a290f1dbb74ba8a911774ff568b6103f61
Signed-off-by: David Vincze <david.vincze@arm.com>