Crypto: Added missing COMPILER_CP_FLAG
As they are required for correct compilation.

Fixes following errors during linking stage:
error: ../bin/tfm_s.axf uses VFP register arguments,
partitions/crypto/tfpsacrypto/core/libtfpsacrypto.a(psa_crypto_aead.o)
does not - failed to merge target specific data of file
partitions/crypto/tfpsacrypto/core/libtfpsacrypto.a(psa_crypto_aead.o)

Change-Id: I396a3b3f8ff7d16e2f3117e333d1e64586861ef7
Signed-off-by: Bohdan Hunko <Bohdan.Hunko@infineon.com>